version: '3'
services:
  node:
    build: .
    restart: always
    ports:
            - "8080:8080"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/home/node
      - /home/node/node_modules
